"""Write the fw_config.ini that fw_native/dxgi.dll reads at boot.

One file per game directory (Side A = Steam FO4, Side B = FO4_b). The
filename is always `fw_config.ini` next to the DLL; contents differ by
side because peer_id and ghost_map entry flip.

Called by `orchestrator.run()` just before launching FO4. Idempotent.
"""
from __future__ import annotations

from pathlib import Path

from launcher import config


TEMPLATE = """\
# FalloutWorld native DLL config — auto-generated by launcher, do not edit.
# (Edits survive until the next launcher run, then get overwritten.)

server = {server_host}:{server_port}
client_id = {client_id}
ghost_map = {ghost_peer}=0x{ghost_formid:X}
log_level = {log_level}

# B3.b auto-load: if non-empty, the DLL hooks the MainMenu registrar and,
# once engine init is complete, directly invokes the engine's LoadGame
# native with this save name. The main menu never shows. Leave empty to
# disable (the main menu will appear normally).
#
# The save name is the filename (no path, no .fos extension) from
# %USERPROFILE%\\Documents\\My Games\\Fallout4\\Saves\\.
auto_load_save = {auto_load_save}

# v19 PIENUVO auth. Minted by the external launcher per-login:
# pubkeyhex:challengehex:sighex (64:64:128 chars). The DLL forwards the
# triple verbatim in HELLO; it does no crypto. Empty = unauthenticated
# session (manual start without the launcher).
auth_blob = {auth_blob}
# Cosmetic display name shown to other players. Identity is the key above.
player_name = {player_name}

# Build 69 A/B — mirror combat suppression (c.36b). true = shipping behaviour:
# a non-owner writes 1 to HighProcess+0x189 on every mirrored NPC each frame.
# That byte is the engine's own StopCombat request flag, and the hp-churn probe
# measured the result: 0 of 181,728 sampled ticks kept it, and all 106
# HighProcess allocations died within 1 tick.
# Set to false to run the control experiment (expect mirrors to aim at you and
# the combat-crouch sliding to come back while it is off).
suppress_mirror_combat = {suppress_mirror_combat}

# 2026-08-05 — first-person ghost animation. BOTH DEFAULT OFF.
# In first person the engine deactivates the third-person animation graph, so
# the 3P skeleton stops producing poses and the peer's ghost freezes.
# first_person_graph_drive revives that graph and runs the engine's own
# per-frame sequence on it. Tried live: the graph revives and every call runs
# clean, but the bones still do not move — and the attempt regressed
# third-person WASD movement. Off until the remaining gate is found.
# stream_pose_in_first_person decides what the SENDER does meanwhile:
#   false = HOLD (ship nothing; the ghost keeps its last good 3P pose — the
#           only first-person state that has ever looked correct)
#   true  = keep streaming; only useful for diagnostics.
first_person_graph_drive = {first_person_graph_drive}
stream_pose_in_first_person = {stream_pose_in_first_person}
"""


def write_for_side(
    side: config.SideConfig,
    *,
    log_level: str = "info",
    auto_load_save: str = "",
    server_addr: str | None = None,
    auth_blob: str = "",
    player_name: str = "",
    client_id: str | None = None,
    suppress_mirror_combat: bool = True,
    first_person_graph_drive: bool = True,
    stream_pose_in_first_person: bool = False,
) -> Path:
    """Write fw_config.ini into the game directory that holds `side.launcher_exe`.

    `auto_load_save` is the bare save filename to direct-load at boot via the
    engine LoadGame native (B3.b). Empty string = feature disabled.

    Returns the path written."""
    game_dir = side.launcher_exe.parent
    path = game_dir / "fw_config.ini"
    # `server_addr` is the whole point of the external launcher: the player
    # picks a row in the server browser and the game must boot pointed at THAT
    # address. Without it the DLL always connected to the hardcoded
    # config.SERVER_HOST:SERVER_PORT, which only ever worked for local testing.
    if server_addr:
        host, _, port_s = server_addr.rpartition(":")
        srv_host, srv_port = host, int(port_s)
    else:
        srv_host, srv_port = config.SERVER_HOST, config.SERVER_PORT
    # v19: the external launcher derives a per-identity client_id, because
    # every launcher-started game used to send the hardcoded "player_A" —
    # two players collided on peer_id_taken and a public server could hold
    # exactly one of them.
    content = TEMPLATE.format(
        server_host=srv_host,
        server_port=srv_port,
        client_id=(client_id or side.peer_id),
        ghost_peer=side.other_peer_id,
        ghost_formid=side.ghost_formid,
        log_level=log_level,
        auto_load_save=auto_load_save,
        auth_blob=auth_blob,
        player_name=player_name,
        suppress_mirror_combat=("true" if suppress_mirror_combat else "false"),
        first_person_graph_drive=(
            "true" if first_person_graph_drive else "false"),
        stream_pose_in_first_person=(
            "true" if stream_pose_in_first_person else "false"),
    )
    path.write_text(content, encoding="utf-8")
    return path
