"""Write the fw_config.ini that fw_native/dxgi.dll reads at boot.

One file per game directory (Side A = Steam FO4, Side B = FO4_b). The
filename is always `fw_config.ini` next to the DLL; contents differ by
side because peer_id and ghost_map entry flip.

Called by `orchestrator.run()` just before launching FO4. Idempotent.
"""
from __future__ import annotations

from pathlib import Path

from launcher import config


TEMPLATE = """\
# FalloutWorld native DLL config — auto-generated by launcher, do not edit.
# (Edits survive until the next launcher run, then get overwritten.)

server = {server_host}:{server_port}
client_id = {client_id}
ghost_map = {ghost_peer}=0x{ghost_formid:X}
log_level = {log_level}

# B3.b auto-load: if non-empty, the DLL hooks the MainMenu registrar and,
# once engine init is complete, directly invokes the engine's LoadGame
# native with this save name. The main menu never shows. Leave empty to
# disable (the main menu will appear normally).
#
# The save name is the filename (no path, no .fos extension) from
# %USERPROFILE%\\Documents\\My Games\\Fallout4\\Saves\\.
auto_load_save = {auto_load_save}
"""


def write_for_side(
    side: config.SideConfig,
    *,
    log_level: str = "info",
    auto_load_save: str = "",
) -> Path:
    """Write fw_config.ini into the game directory that holds `side.launcher_exe`.

    `auto_load_save` is the bare save filename to direct-load at boot via the
    engine LoadGame native (B3.b). Empty string = feature disabled.

    Returns the path written."""
    game_dir = side.launcher_exe.parent
    path = game_dir / "fw_config.ini"
    content = TEMPLATE.format(
        server_host=config.SERVER_HOST,
        server_port=config.SERVER_PORT,
        client_id=side.peer_id,
        ghost_peer=side.other_peer_id,
        ghost_formid=side.ghost_formid,
        log_level=log_level,
        auto_load_save=auto_load_save,
    )
    path.write_text(content, encoding="utf-8")
    return path
